### ISSUE TITLE
Installation and Runtime Issues @ Neurotechnology Lab

### ISSUE THREAD

**Issue by damaggu** [IBT-FMI/COSplay#16]
setuptools should be listed as dependency, whereas it is not. Under python 2.7 `setup` can be imported from `distutils.core`, but this is not able to correctly set up the package, as it does not understand e.g. entry points. `distutils.core` can also not provide `find packages`, but this import is apparently not needed - right?

After installing python2.7.14, pyserial3.4 and setuptools36.5.0, and setting up the package, we got the following error:

```
[mri@CZC5064MR2 ~]$ COSplay 
Traceback (most recent call last):
  File "/home/mri/.local/bin/COSplay", line 11, in <module>
    load_entry_point('COSplay==0.0.0', 'console_scripts', 'COSplay')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 570, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2750, in load_entry_point
ImportError: Entry point ('console_scripts', 'COSplay') not found
```

Additionally, even when executing as `python2.7 cosplay/cli.py`(and after having run the permission granting scripts as superuser), the software cannot find the device. Not least of all there is a typo with the respective prompt ("Seraching").

**Comment by TheChymera** [comment]
- [x] typo ( fixed 77eaf147cfd71cf3bc48e56c5023f39008f7cc27 )
- [ ] `setuptools` dependency and `find_packages` import (possibly need feedback from @faymanns 
- [ ] entry point not found for `COSplay` command - definitely need feedback from @faymanns 
- [ ] computer-side script not finding the device - definitely need feedback from @faymanns

**Comment by faymanns** [comment]
- `find_packages` is not needed. Once we figured out why the entry point is not found, I'll add the correct dependencies.

-  So far I was not able to reproduce the error on my computer. I'll look into it some more tomorrow.

- My guess is that it doesn't find the device because your user doesn't have the right permissions to write to the device node of the the system (usually `/dev/ttyACM0`). In order to always grant the right permissions when you connect the system you can run [this script](https://github.com/IBT-FMI/COSplay/blob/master/scripts/grant_permissions_for_pyboard) which comes with COSplay. It'll create a new udev rule for Micropython devices. Note: If you don't feel comfortable running the script as sudo or root, you can creat the udev rule manually.

**Comment by faymanns** [comment]
I still was able to reproduce the error on my computer.
Can you install it using this command
`sudo python setup.py install --record files.txt`
and tell me what it says in `filtes.txt` afterwards?
These are the files it installs when I run the command.
```
/usr/local/lib/python2.7/site-packages/COSplay-0.0.0-py2.7.egg
/usr/local/bin/grant_permissions_for_pyboard
/usr/local/bin/COSplay
```

**Comment by TheChymera** [comment]
@faymanns I remember we ran the permissions script as root.

I'm not at Irchel atm, and Markus has left for 2 weeks. Would you have time to drop by tomorrow and try to install it with me?

**Comment by TheChymera** [comment]
Installed python 2.7 and setuptools at the system level. Maybe we should add a short "install guide" to the README, where we advise people to make the deps globally accessible, and diffuse the most common worry (that the system may get messed up) via our own examples.
