### ISSUE TITLE
sudden and permanent crash after sequence update 

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSplay#7]
So, this just happened:

* I copied a new sequence (which you can see [here](http://chymera.eu/debug/cosplay/sequence_.tsv)) to `/mountpoint/sequence_library/`; I waited a bit, prepared the experiment and then tried to delete the previous sequence file, only to find that **the filesystem got mounted read-only on all attempts on all USB ports**

* I tried to start the stimulation manually to see which stimulation protocol it would choose and **it crashed with alternating red and green lights imediately after I gave it a manual trigger every time I tried** 

* I mounted the filesystem manually to get write access, deleted both my new stimulation file an the abbreviated stimulation file we had previously tested, and placed only the [example file](https://github.com/IBT-FMI/COSplay/blob/6d360cd80dcf4c54d93d88bc8ec9ac0e90552985/sequence.tsv) inside the sequence library. Subsequenty, the system **no longer crashed upon triggering, but instead executesd an almost instantaneous protocol, after which it was ready to be armed again**.

* After an hour or so, I tried to test the behaviour again, and now, **the board invariably crashes with alternating red and green lights immediately after I first push the middle button to have it select the present sequence**.

In addition to fixing it soon, I recommend you try to repeat my steps, and make the needed modifications to avert this sort of crash permanently. The use case "write a manual sequence and just drop it in the right path" doesn't seem well covered and stress-tested at the moment.

**Comment by faymanns** [comment]
I know about the mounting as read-only. This also happens on my Ubuntu system from time to time. The reason for it is that we tell the pyboard to operate in mass storage and virtual com port mode simultaneously, instead of just virtual com port. I tried to address this issue a while back and suggested we only mount it in virtual com port mode. This would mean you cannot manually copy sequences to the board anymore. You said that this feature is absolutely essential, and I agree that it is an important feature.
You can avoid this bug if you really take care when operating the board (always unmount before reseting the board and so on).
I don't see any other way, but to abolish the manual copying to make the system more stable. This is because we cannot control when which of the systems (pyboard and host computer) accesses the files (race conditions).
'pythoncoder' also mentioned this issue in a reply to my [question](https://forum.micropython.org/viewtopic.php?f=2&t=3233) on the micropython forum.
I can try to do a bit more digging, but I am quite sure there is no other solution than dropping manual copying of sequences.

What I usually to fix this issue is to format the sd card and copy the files from the repository to it.

**Comment by TheChymera** [comment]
> What I usually to fix this issue is to format the sd card and copy the files from the repository to it.

Oh my, we should absolutely avoid exposing users to this sort of fix. Perhaps a workaround can be found, which also allows us to keep the feature? Like copying the stimulation file to the COSgen directory, which the COSplay script then watches? This means that the functionality would be contingent on the script being installed, though...

Perhaps some other way?

**Comment by faymanns** [comment]
I'll look into it tomorrow.
As for the red and green leds flashing, that means an error occurred on the pyboard. Generally you should be able to find error message in `exceptions.txt` on the sd card. We can check the file on Monday and try to see if the error is connected to the read only issue. Maybe one of the files was corrupted?

**Comment by faymanns** [comment]
I just checked the [exceptions.txt](https://github.com/IBT-FMI/COSplay/files/1000488/exceptions.txt). It appears that the pyboard did not load the sequence file properly, which makes sense, as the sequence file seems to be corrupted and just contains gibberish. (I cannot upload it here because github doesn't support uploading corrupted files.)
First of all I think we should move the program form the SD card to the internal flash memory to safeguard the program files and only use the SD card for sequence files.
As for copying, we could use the switch to select a mode in which it is safe to copy. For example we could flash an LED for 2 seconds after resetting the board and if you press the USR button during that time the pyboard boots in a 'safe to copy' mode and otherwise runs the program as it is now in virtual comm port mode.

**Comment by faymanns** [comment]
Another approach could be to used Dave Hylands [rshell](https://github.com/dhylands/rshell). This requires python3 though. For users familiar with shell and python this would be the best approach, as it is the most versatile.

**Comment by TheChymera** [comment]
Moving the problem is a good idea, likely without any major drawbacks.

Branching the use cases so as to disentangle comm port and mass storage use is indeed a good idea, but I am concerned about complicating the workflow by requiring more interaction. Can't we make this dependent on whether or not there is a client script on the computer? (if there is, copying directly to the card is not needed; if there isn't, it's clear that mass storage mode will be needed... but the  again, the pyboard will still need to write to itself to save the output sequence)

Another solution may be to create 2 partitions on the SD card (can the pyboard support this?) one to which the pyboard writes the used sequence, and one to which the user/script can write the to-be-delivered sequences.   

I don't think it would be good to require python 3 and to not have a file browser (drag&drop) access.

**Comment by faymanns** [comment]
I don't think it is possible to change the usb mode once it is selected, meaning it is not possible to detect the client script and change usb mode accordingly.

I tried the pyboard does not support 2 partitions on the SD card.

**Comment by faymanns** [comment]
IMHO we should use the button. If the client script runs on the computer, it would not change the work flow at all. It would simply slow down the start up of the board two or three seconds (i.e. the window when you can press the button to enter copy mode).

**Comment by TheChymera** [comment]
You're welcome to link the appropriate commits for reference if you want, but based on present testing results I'd say the issue got solved.
